CREATE DATABASE php-todo;
USE php-todo;
CREATE TABLE todo (
	id INT(10) NOT NULL AUTO_INCREMENT,
	todo VARCHAR(255) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (id) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=34
;